name: SimpleAntiSpam
version: ${project.version}
main: me.hsgamer.simpleantispam.SimpleAntiSpam
api-version: 1.16
authors: [ HSGamer ]
description: Block spam and repeating messages
permissions:
  simpleantispam.bypass:
    default: op
    description: Bypass the detection